# Generated by Django 3.0 on 2020-01-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='data',
            field=models.FileField(default='To be Added', upload_to=''),
        ),
    ]
