# Generated by Django 3.0 on 2020-01-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='data',
            field=models.FileField(default='To be Added', upload_to='documents/'),
        ),
    ]
